Fix UnboundLocalError
Why:

'pk_over_idivf' needs to be defined before the if statement, otherwise it
produces an error:
UnboundLocalError: local variable 'pk_over_idivf' referenced before assignment

This change addresses the need by:

* Moving it outside of the if statement.